### ISSUE TITLE
rewrite tonatona-logger to not contain the logginer function in the Shared data type

### ISSUE THREAD

**Issue by cdepillabout** [arow-oss/tonatona#12]
Currently, the `tonatona-logger` package is similar to `tonatona-email` and `tonatona-db` in that the `Shared` type contains a function to actually do the logging:

https://github.com/arow-oss/tonatona/blob/f4641d86d14e8c478d0d2cf3705d4c4d9478a925/tonatona-logger/src/Tonatona/Logger.hs#L54-L56

@arowM This should be relatively easy to change to only contain a pure, non-function value.  Should I make this change?

**Comment by arowM** [comment]
I think it would be better to make the `Shared` type only contain minimal core shared data.
But I don't know whether we should limit the value to be a pure non-function value.

**Comment by arowM** [comment]
`Shared` was removed by #32, so I'll close this issue.
