### ISSUE TITLE
Proposal: Quit to use redundant type names

### ISSUE THREAD

**Issue by arowM** [arow-oss/tonatona#13]
Current tonatona plugins has type names that contains its module name such as `Tonatona.Db.TonaDbShared`, `Tonatona.Servant.TonaServantConfig`, `Tonatona.Db.TonaDbM`, etc.
Though it is me who at first introduced such naming rule, I currently think it is not good.
The reason I think so is bellow.

* It would be too long on some modules
    * e.g., In `Tonatona.Foo.Bar.Baz.FooBaz`, the name would be something like `TonaFooBarBazFooBazShared`
* It is not suit for qualified import
    * Tonatona plugins are supposed to be imported qualified, so those names are too redundant

The type names such as `Tonatona.*.HasShared`, `Tonatona.*.HasConfig`, `Tonatona.*.Action` would be better.

**Comment by arowM** [comment]
@cdepillabout What do you think about this policy?

**Comment by cdepillabout** [comment]
I think this sounds good.  I'll send a PR implementing this.
