### ISSUE TITLE
Hide short hand arguments before publishing

### ISSUE THREAD

**Issue by arowM** [arow-oss/tonatona#27]
I'm not sure we should do this.

How about hiding tonaparser feature regarding to short hand command line arguments?
Current design of tonaparser has relatively big problem that short hand arguments do not consider real use cases as referred in https://github.com/arow-oss/tonatona/issues/24.

If tonaparser contains current implementation for short hand arguments, it means we have to do destructive library update soon after release.
It breaks our goal mentioned in README:
> The most important goal of Tonatona is to make development speed fast and maintenance cost low.
Actually it increases maintenance cost.

@cdepillabout What do you think about it?

**Comment by cdepillabout** [comment]
> How about hiding tonaparser feature regarding to short hand command line arguments?

I think this would be easy to do.  I don't know if exposing short hand arguments really adds that much value to the end-user.

We could also just completely redo tonaparser and have it work much more like optparser-applicative (as specified in #24).  That would be the "better" solution, but it would take more time than just removing the short hand arguments.

Should we just go ahead and remove the short-hand arguments for now?

**Comment by cdepillabout** [comment]
I came up with a small example of what it might look like to adopt an optparse-applicative style for parsing command line arguments and environment variables.

It is implemented on branch [example-optparse-applicative](https://github.com/arow-oss/tonatona/tree/example-optparse-applicative)(and in particular commit 7fbc43b0ebc59d1).  This shows most of the user-facing changes that will need to take place.  However, the internals of tonaparser will probably have to majorly change as well.  Also, this implements only a small fraction of all the options available with optparse-applicative.  If we wanted to support all the possible options of optparse-applicative, it might be a good idea to change the API a little more.

(In particular, optparse-applicative has a concept of "subcommands" that we don't need to support.  This is like how `git` has subcommands like `add`, `push`, `commit`, etc.  optparse-applicative also provides lots of options for changing the layout of the `--help` text.  optparse-applicative provides different kinds of argument parsers for parsing command line arguments that aren't specified as flags.  If we wanted to support any of these things, the API for tonaparser would probably have to change as well.)

Now, the example could be run any of the following ways (showing some combination of using command line arguments and environment variables):

```sh
$ FOO=2 tonaparser-example
$ tonaparser-example --new-foo 100 --do-something
$ DO_SOMETHING=yes tonaparser-example --new-foo 200 --bar-baz hello
```

It will also show help text if run with `--help`:

```sh
$ tonaparser-example --help
tonaparser-example - An example program that demonstrates tonaparser.

Usage: tonaparser-example [--help] [--bar-baz BAZ] [--new-foo FOO] [--do-something]

This the header for this sample example program.  Just an example.

Available options:
  --help Print this help text.
  --bar-baz BAZ, -c BAZ This is the value to use for baz. Defaults to "mybaz" if not specified.  Also can be specified as NEW_BAR_BAZ env var.
  --new-foo FOO  This is the value to use for foo.  Required. Also can be specified as FOO env var.
  --do-something  Whether or not to do something. If not specified, then do nothing. Can be specified as --no-do-something to disable.  Also can be specified as DO_SOMETHING env var.

Environment variables:
  NEW_BAR_BAZ  This is the value to use for baz. Defaults to "mybaz" if not specified.  Overruled by the --bar-baz command line flag.
  FOO  This is the value to use for foo.  Required. Overruled by the --new-foo command line flag.
  DO_SOMETHING  Whether or not to do something.  If not specified, then do nothing.  Set as DO_SOMETHING=1 to enable, and DO_SOMETHING=0  to disable.  Overruled by the --do-something command line flag.

This is the footer for this sample example program.  Goes at the end.
```

**Comment by arowM** [comment]
Thanks!
It seems we can do same thing by just adding new functions to current API design if we hide functions about short hand arguments.

```haskell

-- This example would be
fromEnv =
    let barOpt =
          strOption
            ( argLong "baz" <>
              argShort 'b' <>
              envVar "BAZ" <>
              defaultVal "mybaz" <>
              helpStr "This is the value to use for baz." <>
              metaVar "BAZ"
            )
    in Bar <$> barOpt

-- realized by current API design by adding `setShort` and `setHelpStr` functions.
fromEnv = Bar
    <$> envDef
        ( argLong "baz" <> setShort 'b' <> setHelpStr "This is the value to use for baz." .||
          envVar "BAZ"
        )
        "mybaz"
```

So, let's just hide functions regarding to short hands arguments.
